version: "3"
services:
  superalgos:
    build: 
      context: ..
      dockerfile: ./Docker/Dockerfile
    image: ghcr.io/superalgos/superalgos:latest
    command: ["minMemo"]
    user: "$UID:$GID"
    ports:
      - '34248:34248'
      - '18041:18041'
    volumes:
      - ../Platform/My-Data-Storage:/app/Platform/My-Data-Storage
      - ../Platform/My-Log-Files:/app/Platform/My-Log-Files
      - ../Platform/My-Workspaces:/app/Platform/My-Workspaces
    restart: on-failure
